name: Ping Supabase to Prevent Pausing
on:
  schedule:
    - cron: '30 18 * * 1' # Runs every Monday at 6:30 PM UTC
    - cron: '30 18 * * 4' # Runs every Thursday at 6:30 PM UTC
    - cron: '30 18 * * 0' # Runs every Sunday at 6:30 PM UTC
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Supabase client
        run: npm install @supabase/supabase-js
      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          node -e "const { createClient } = require('@supabase/supabase-js'); const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY); supabase.from('users2').select('id').limit(1).then(console.log).catch(console.error);"
